/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package siopet;

/**
 *
 * @author nico flassy
 */
import java.awt.Color;
public class card_penitipan extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public card_penitipan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon3 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        harga_penitipan = new javax.swing.JLabel();
        checklist4 = new javax.swing.JLabel();
        checklist3 = new javax.swing.JLabel();
        checklist2 = new javax.swing.JLabel();
        checklist1 = new javax.swing.JLabel();
        keterangan4 = new javax.swing.JLabel();
        keterangan3 = new javax.swing.JLabel();
        keterangan2 = new javax.swing.JLabel();
        keterangan1 = new javax.swing.JLabel();
        nama_penitipan = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 217, 224));
        setLayout(null);

        icon3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        icon3.setForeground(new java.awt.Color(51, 51, 51));
        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fish.png"))); // NOI18N
        add(icon3);
        icon3.setBounds(150, 20, 40, 40);

        icon2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        icon2.setForeground(new java.awt.Color(51, 51, 51));
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bath.png"))); // NOI18N
        add(icon2);
        icon2.setBounds(90, 20, 40, 40);

        icon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        icon1.setForeground(new java.awt.Color(51, 51, 51));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sleep.png"))); // NOI18N
        add(icon1);
        icon1.setBounds(30, 20, 40, 40);

        harga_penitipan.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        harga_penitipan.setForeground(new java.awt.Color(51, 51, 51));
        harga_penitipan.setText("Rp. 45.000");
        add(harga_penitipan);
        harga_penitipan.setBounds(50, 230, 140, 25);

        checklist4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist4.setForeground(new java.awt.Color(51, 51, 51));
        checklist4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist4);
        checklist4.setBounds(33, 190, 20, 19);

        checklist3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist3.setForeground(new java.awt.Color(51, 51, 51));
        checklist3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist3);
        checklist3.setBounds(34, 165, 20, 19);

        checklist2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist2.setForeground(new java.awt.Color(51, 51, 51));
        checklist2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist2);
        checklist2.setBounds(34, 140, 20, 19);

        checklist1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist1.setForeground(new java.awt.Color(51, 51, 51));
        checklist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist1);
        checklist1.setBounds(34, 114, 20, 20);

        keterangan4.setBackground(new Color(61,60,60));
        keterangan4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan4.setForeground(new java.awt.Color(61, 60, 60));
        keterangan4.setText("Keterangan 4");
        add(keterangan4);
        keterangan4.setBounds(66, 185, 120, 25);

        keterangan3.setBackground(new Color(61,60,60));
        keterangan3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan3.setForeground(new java.awt.Color(61, 60, 60));
        keterangan3.setText("Keterangan 3");
        add(keterangan3);
        keterangan3.setBounds(66, 160, 120, 25);

        keterangan2.setBackground(new Color(61,60,60));
        keterangan2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan2.setForeground(new java.awt.Color(61, 60, 60));
        keterangan2.setText("Keterangan 2");
        add(keterangan2);
        keterangan2.setBounds(66, 135, 120, 25);

        keterangan1.setBackground(new Color(61,60,60));
        keterangan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan1.setForeground(new java.awt.Color(61, 60, 60));
        keterangan1.setText("Keterangan 1");
        add(keterangan1);
        keterangan1.setBounds(66, 110, 120, 25);

        nama_penitipan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nama_penitipan.setText("Nama");
        add(nama_penitipan);
        nama_penitipan.setBounds(50, 80, 170, 27);

        bg.setBackground(new Color(0,0,0,0));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/card penitipan.png"))); // NOI18N
        add(bg);
        bg.setBounds(-70, 0, 340, 280);

        bg1.setBackground(new Color(0,0,0,0));
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/card penitipan 2.png"))); // NOI18N
        add(bg1);
        bg1.setBounds(-70, 0, 340, 280);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    public static javax.swing.JLabel checklist1;
    public static javax.swing.JLabel checklist2;
    public static javax.swing.JLabel checklist3;
    public static javax.swing.JLabel checklist4;
    public static javax.swing.JLabel harga_penitipan;
    public static javax.swing.JLabel icon1;
    public static javax.swing.JLabel icon2;
    public static javax.swing.JLabel icon3;
    public static javax.swing.JLabel keterangan1;
    public static javax.swing.JLabel keterangan2;
    public static javax.swing.JLabel keterangan3;
    public static javax.swing.JLabel keterangan4;
    public static javax.swing.JLabel nama_penitipan;
    // End of variables declaration//GEN-END:variables
}
