/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package siopet;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import java.awt.Color;
import javax.swing.JScrollPane;

/**
 *
 * @author nico flassy
 */
public class item_notif extends javax.swing.JPanel {

    /**
     * Creates new form item_notif
     */
    public item_notif(String judul,String keterangan) {
        initComponents();
        judul_notif.setText(judul);
        keterangan_notif.setText(keterangan);
        keterangan_notif.setLineWrap(true);
        keterangan_notif.setWrapStyleWord(true);
        keterangan_notif.setEditable(false);
        keterangan_notif.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        judul_notif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        keterangan_notif = new javax.swing.JTextArea();

        jScrollPane1.setViewportView(jTextPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        judul_notif.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        judul_notif.setText("judul_notif");
        add(judul_notif);
        judul_notif.setBounds(12, 10, 360, 21);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("____________________________________________________________");
        jLabel1.setToolTipText("");
        add(jLabel1);
        jLabel1.setBounds(10, 60, 360, 20);

        keterangan_notif.setBackground(new java.awt.Color(255, 255, 255));
        keterangan_notif.setColumns(20);
        keterangan_notif.setForeground(new java.awt.Color(0, 0, 0));
        keterangan_notif.setRows(5);
        keterangan_notif.setText("Barang hampir habis, segera restock barang!");
        keterangan_notif.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        keterangan_notif.setCaretColor(new Color(0,0,0,0));
        add(keterangan_notif);
        keterangan_notif.setBounds(12, 30, 360, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    public static javax.swing.JLabel judul_notif;
    public static javax.swing.JTextArea keterangan_notif;
    // End of variables declaration//GEN-END:variables
}
