/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package siopet.Admin;

/**
 *
 * @author nico flassy
 */
import siopet.*;
import java.awt.Color;
public class card_gromming extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public card_gromming() {
        initComponents();
        bg_gromming_kucing.setVisible(false);
        bg_gromming_anjing.setVisible(false);
        bg_gromming_domestik.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harga_barang = new javax.swing.JLabel();
        checklist4 = new javax.swing.JLabel();
        checklist3 = new javax.swing.JLabel();
        checklist2 = new javax.swing.JLabel();
        checklist1 = new javax.swing.JLabel();
        keterangan4 = new javax.swing.JLabel();
        keterangan3 = new javax.swing.JLabel();
        keterangan2 = new javax.swing.JLabel();
        keterangan1 = new javax.swing.JLabel();
        nama_gromming = new javax.swing.JLabel();
        bg_gromming_domestik = new javax.swing.JLabel();
        bg_gromming_anjing = new javax.swing.JLabel();
        bg_gromming_kucing = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setLayout(null);

        harga_barang.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        harga_barang.setForeground(new java.awt.Color(51, 51, 51));
        harga_barang.setText("Rp. 45.000");
        add(harga_barang);
        harga_barang.setBounds(50, 270, 140, 25);

        checklist4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist4.setForeground(new java.awt.Color(51, 51, 51));
        checklist4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist4);
        checklist4.setBounds(34, 240, 20, 20);

        checklist3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist3.setForeground(new java.awt.Color(51, 51, 51));
        checklist3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist3);
        checklist3.setBounds(34, 215, 20, 20);

        checklist2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist2.setForeground(new java.awt.Color(51, 51, 51));
        checklist2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist2);
        checklist2.setBounds(34, 190, 20, 20);

        checklist1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checklist1.setForeground(new java.awt.Color(51, 51, 51));
        checklist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checklist 1.png"))); // NOI18N
        add(checklist1);
        checklist1.setBounds(33, 165, 20, 19);

        keterangan4.setBackground(new Color(61,60,60));
        keterangan4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan4.setForeground(new java.awt.Color(61, 60, 60));
        keterangan4.setText("Keterangan 4");
        add(keterangan4);
        keterangan4.setBounds(66, 235, 120, 25);

        keterangan3.setBackground(new Color(61,60,60));
        keterangan3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan3.setForeground(new java.awt.Color(61, 60, 60));
        keterangan3.setText("Keterangan 3");
        add(keterangan3);
        keterangan3.setBounds(66, 210, 120, 25);

        keterangan2.setBackground(new Color(61,60,60));
        keterangan2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan2.setForeground(new java.awt.Color(61, 60, 60));
        keterangan2.setText("Keterangan 2");
        add(keterangan2);
        keterangan2.setBounds(66, 185, 120, 25);

        keterangan1.setBackground(new Color(61,60,60));
        keterangan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keterangan1.setForeground(new java.awt.Color(61, 60, 60));
        keterangan1.setText("Keterangan 1");
        add(keterangan1);
        keterangan1.setBounds(66, 160, 120, 25);

        nama_gromming.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nama_gromming.setText("Nama Gromming");
        add(nama_gromming);
        nama_gromming.setBounds(30, 130, 170, 25);

        bg_gromming_domestik.setBackground(new Color(0,0,0,0));
        bg_gromming_domestik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/card gromming domestik.png"))); // NOI18N
        add(bg_gromming_domestik);
        bg_gromming_domestik.setBounds(-70, 0, 290, 360);

        bg_gromming_anjing.setBackground(new Color(0,0,0,0));
        bg_gromming_anjing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/card gromming anjing.png"))); // NOI18N
        add(bg_gromming_anjing);
        bg_gromming_anjing.setBounds(-70, 0, 290, 360);

        bg_gromming_kucing.setBackground(new Color(0,0,0,0));
        bg_gromming_kucing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/card gromming kucing.png"))); // NOI18N
        add(bg_gromming_kucing);
        bg_gromming_kucing.setBounds(-70, 0, 290, 360);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel bg_gromming_anjing;
    public static javax.swing.JLabel bg_gromming_domestik;
    public static javax.swing.JLabel bg_gromming_kucing;
    public static javax.swing.JLabel checklist1;
    public static javax.swing.JLabel checklist2;
    public static javax.swing.JLabel checklist3;
    public static javax.swing.JLabel checklist4;
    public static javax.swing.JLabel harga_barang;
    public static javax.swing.JLabel keterangan1;
    public static javax.swing.JLabel keterangan2;
    public static javax.swing.JLabel keterangan3;
    public static javax.swing.JLabel keterangan4;
    public static javax.swing.JLabel nama_gromming;
    // End of variables declaration//GEN-END:variables
}
